#!/bin/bash

if [ "$EUID" != "0" ]; then
  echo "You must be root to run this script. Sorry, dude!"
  exit 1
fi

LXCDIR="/var/lib/lxc"
CONFIG="config"

# Setup LXC and base container
apt-get -y --force-yes install lxc
mkdir -p $LXCDIR
lxc-create -t ubuntu -n base

chroot $LXCDIR/base/rootfs apt-get update
# !!!
# ADD THE PACKETS YOU NEED TO INSTALL HERE
# !!!
chroot $LXCDIR/base/rootfs apt-get -y --force-yes install libboost-thread-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev rsyslog vlan tcpdump quagga
apt-get install git-core autoconf libtool gawk xterm texinfo libreadline6 libreadline6-dev gcc
git clone https://github.com/vdham/quagga-public-kamboi.git
cd quagga-public-kamboi
git checkout ldp_v1.0
./bootstrap.sh
./configure --enable-mpls=null --sysconfdir=/etc/quagga --localstatedir=/var/run/quagga --prefix=$LXCDIR/base/rootfs/usr --enable-fpm --enable-vtysh
make
make install

# !!!
# Clone the base container to make other containers based on config
cd ./..
cd $CONFIG
for VM in *
do
    lxc-clone -o base -n $VM
    cp -R $VM/* $LXCDIR/$VM
done
